# Generated by Django 4.2.3 on 2023-10-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_userr_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
